name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b
        with:
          generate_release_notes: true
